FROM ghcr.io/seisscoped/container-base:centos7

LABEL maintainer="Yiyu Ni"

RUN  cd /home/scoped \
    && git clone --depth=1 git@github.com:congcy/ELEP.git \
    && cd ELEP \
    && git pull \
    && pip install . \
    && docker-clean 